version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:Ra62052Sa%40@db/CMS_db
      - SECRET_KEY=ocrolus_secret_key
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
        - MYSQL_DATABASE=CMS_db
        - MYSQL_ROOT_PASSWORD=Ra62052Sa@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
